### ISSUE TITLE
[BUG] The New Cats

### ISSUE THREAD

**Issue by Hallowen12** [shaggyze/uotiara#3]
I get an error that crashes my game displaying "invalid data skill" upon summoning the new Cat.

**Comment by shaggyze** [comment]
> I get an error that crashes my game displaying "invalid data skill" upon summoning the new Cat.

Since this is your second time posting an issue of a Bug of this kind let me clarify by saying this is not a bug, it is an intended result of you using outdated mods, there will be half a dozen things like this that will occur after a major update.

Disable the data folder with Abyss or Kanan and/or delete your data folder until I have updated it.

Should be fixed in release 417.

**Comment by shaggyze** [comment]
> I get an error that crashes my game displaying "invalid data skill" upon summoning the new Cat.

Since this is your second time posting an issue of a Bug of this kind let me clarify by saying this is not a bug, it is an intended result of you using outdated mods, there will be half a dozen things like this that will occur after a major update.

Disable the data folder with Abyss or Kanan, delete your data folder and/or uotiara_00001.it in your package folder until I have updated it.

Should be fixed in release 417.
